pipeline {
    agent any
    tools{
        maven 'maven3.9.6'
    }

    stages {
        stage('git checkout') {
            steps {
                git branch: 'helm-charts', credentialsId: 'gitcredentials', url: 'https://github.com/Teju950/microservices-apps.git'
            }
        }
        stage('Build') {
            steps {
                dir('shoes-microservice-spring-boot'){
                     sh 'mvn clean install' 
                }
            }
        }
        stage('Build and push image') {
            environment {
                DOCKER_REGISTRY_CREDENTIALS = credentials('Dockercredentials')
                DOCKER_IMAGE = "teju792/shoesapp:${BUILD_NUMBER}"
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'Dockercredentials') {
                        dir('shoes-microservice-spring-boot'){
                        sh "docker login -u $DOCKER_REGISTRY_CREDENTIALS_USR -p $DOCKER_REGISTRY_CREDENTIALS_PSW"
                        sh "docker build -t ${DOCKER_IMAGE} ."
                        sh "docker push ${DOCKER_IMAGE}"
                        sh "docker rmi ${DOCKER_IMAGE}"
                        }
                    }
                }
            }
        }
    }
}
