apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-21T05:29:53Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2024-01-26T13:12:54Z"
  generateName: argocd-server-58f5668765-
  labels:
    app.kubernetes.io/name: argocd-server
    pod-template-hash: 58f5668765
  name: argocd-server-58f5668765-chl7z
  namespace: argocd
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: argocd-server-58f5668765
    uid: c83e000e-a193-48a0-9b25-53e436b73b96
  resourceVersion: "2029467"
  uid: c1659abe-9eb5-40a7-84a4-b29eca75aab3
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: argocd-server
          topologyKey: kubernetes.io/hostname
        weight: 100
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: argocd
          topologyKey: kubernetes.io/hostname
        weight: 5
  containers:
  - args:
    - /usr/local/bin/argocd-server
    env:
    - name: ARGOCD_SERVER_INSECURE
      valueFrom:
        configMapKeyRef:
          key: server.insecure
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_BASEHREF
      valueFrom:
        configMapKeyRef:
          key: server.basehref
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_ROOTPATH
      valueFrom:
        configMapKeyRef:
          key: server.rootpath
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_LOGFORMAT
      valueFrom:
        configMapKeyRef:
          key: server.log.format
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          key: server.log.level
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_REPO_SERVER
      valueFrom:
        configMapKeyRef:
          key: repo.server
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_DEX_SERVER
      valueFrom:
        configMapKeyRef:
          key: server.dex.server
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_DISABLE_AUTH
      valueFrom:
        configMapKeyRef:
          key: server.disable.auth
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_ENABLE_GZIP
      valueFrom:
        configMapKeyRef:
          key: server.enable.gzip
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_REPO_SERVER_TIMEOUT_SECONDS
      valueFrom:
        configMapKeyRef:
          key: server.repo.server.timeout.seconds
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_X_FRAME_OPTIONS
      valueFrom:
        configMapKeyRef:
          key: server.x.frame.options
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_CONTENT_SECURITY_POLICY
      valueFrom:
        configMapKeyRef:
          key: server.content.security.policy
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_REPO_SERVER_PLAINTEXT
      valueFrom:
        configMapKeyRef:
          key: server.repo.server.plaintext
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_REPO_SERVER_STRICT_TLS
      valueFrom:
        configMapKeyRef:
          key: server.repo.server.strict.tls
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_DEX_SERVER_PLAINTEXT
      valueFrom:
        configMapKeyRef:
          key: server.dex.server.plaintext
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_DEX_SERVER_STRICT_TLS
      valueFrom:
        configMapKeyRef:
          key: server.dex.server.strict.tls
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_TLS_MIN_VERSION
      valueFrom:
        configMapKeyRef:
          key: server.tls.minversion
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_TLS_MAX_VERSION
      valueFrom:
        configMapKeyRef:
          key: server.tls.maxversion
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_TLS_CIPHERS
      valueFrom:
        configMapKeyRef:
          key: server.tls.ciphers
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_CONNECTION_STATUS_CACHE_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: server.connection.status.cache.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_OIDC_CACHE_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: server.oidc.cache.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_LOGIN_ATTEMPTS_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: server.login.attempts.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_STATIC_ASSETS
      valueFrom:
        configMapKeyRef:
          key: server.staticassets
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_APP_STATE_CACHE_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: server.app.state.cache.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: REDIS_SERVER
      valueFrom:
        configMapKeyRef:
          key: redis.server
          name: argocd-cmd-params-cm
          optional: true
    - name: REDIS_COMPRESSION
      valueFrom:
        configMapKeyRef:
          key: redis.compression
          name: argocd-cmd-params-cm
          optional: true
    - name: REDISDB
      valueFrom:
        configMapKeyRef:
          key: redis.db
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_DEFAULT_CACHE_EXPIRATION
      valueFrom:
        configMapKeyRef:
          key: server.default.cache.expiration
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_MAX_COOKIE_NUMBER
      valueFrom:
        configMapKeyRef:
          key: server.http.cookie.maxnumber
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_LISTEN_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: server.listen.address
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_METRICS_LISTEN_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: server.metrics.listen.address
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_OTLP_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: otlp.address
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_APPLICATION_NAMESPACES
      valueFrom:
        configMapKeyRef:
          key: application.namespaces
          name: argocd-cmd-params-cm
          optional: true
    - name: ARGOCD_SERVER_ENABLE_PROXY_EXTENSION
      valueFrom:
        configMapKeyRef:
          key: server.enable.proxy.extension
          name: argocd-cmd-params-cm
          optional: true
    image: quay.io/argoproj/argocd:v2.9.3
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz?full=true
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    name: argocd-server
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8083
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /app/config/ssh
      name: ssh-known-hosts
    - mountPath: /app/config/tls
      name: tls-certs
    - mountPath: /app/config/server/tls
      name: argocd-repo-server-tls
    - mountPath: /app/config/dex/tls
      name: argocd-dex-server-tls
    - mountPath: /home/argocd
      name: plugins-home
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nhb2l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-31-38-62.ap-south-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: argocd-server
  serviceAccountName: argocd-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: plugins-home
  - emptyDir: {}
    name: tmp
  - configMap:
      defaultMode: 420
      name: argocd-ssh-known-hosts-cm
    name: ssh-known-hosts
  - configMap:
      defaultMode: 420
      name: argocd-tls-certs-cm
    name: tls-certs
  - name: argocd-repo-server-tls
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
      - key: ca.crt
        path: ca.crt
      optional: true
      secretName: argocd-repo-server-tls
  - name: argocd-dex-server-tls
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: tls.crt
      - key: ca.crt
        path: ca.crt
      optional: true
      secretName: argocd-dex-server-tls
  - name: kube-api-access-nhb2l
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-21T05:29:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-26T13:07:18Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-21T05:30:24Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-21T05:29:53Z"
    status: "True"
    type: PodScheduled
  - lastProbeTime: null
    lastTransitionTime: "2024-01-26T13:12:24Z"
    message: 'Taint manager: deleting due to NoExecute taint'
    reason: DeletionByTaintManager
    status: "True"
    type: DisruptionTarget
  containerStatuses:
  - containerID: containerd://06a1eeb6b71c71d2e4cdb358c184777e42934c4ff87362f794ce853e322c6251
    image: quay.io/argoproj/argocd:v2.9.3
    imageID: quay.io/argoproj/argocd@sha256:dfc13f4b9ddbf25a88f7018667ee45e35a49520e2716242e3f65ef75f88c25ff
    lastState: {}
    name: argocd-server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-21T05:30:05Z"
  hostIP: 172.31.38.62
  phase: Running
  podIP: 172.31.34.186
  podIPs:
  - ip: 172.31.34.186
  qosClass: BestEffort
  startTime: "2024-01-21T05:29:53Z"
