
replicaCount: 2

image:
  repository: "teju792/dockerpracticee"
  tag: "v1"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.


service:
  type: NodePort
  port: 8080
  targetport: 8080

container:
  name: "react-ui"