
replicaCount: 2

image:
  repository: teju792/dockerpracticee
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

service:
  type: NodePort
  port: 8080
  targetport: 8080

container:
  name: react-ui