apiVersion: v1
kind: Service
metadata:
  name:  reactjs-service
spec:
  type: NodePort
  ports:
  - port: 8080          # Port exposed within the cluster
    targetPort: 8080  # Port on the pods
    nodePort: 30011   # Port accessible externally on each node
  selector:
    app: reactjs-app